# Generated by Django 4.2 on 2023-05-03 19:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_customuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='showing',
            name='time',
            field=models.TimeField(default=datetime.time, verbose_name='showing time'),
        ),
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.CharField(choices=[('condo', 'Condominium'), ('house', 'House')], default='condo', max_length=10),
        ),
        migrations.AlterField(
            model_name='showing',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='showing date'),
        ),
    ]
