# Generated by Django 4.2.30 on 2026-08-17 16:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_customuser_favorites_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='showing',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='showing date'),
        ),
    ]
